GET http://localhost:3000/posts
###
GET http://localhost:3000/api/tutorials/:id
###
POST http://localhost:3000/user
Content-Type: application/json
{
"title" : "wa wa wa"
}
###
PUT http://localhost:3000/api/posts/:id
###
DELETE  http://localhost:3000/api/posts/:id
###
DELETE  http://localhost:3000/api/posts
###
GET http://localhost:3000/api/posts?title=[kw]